'use strict';
const algebraTopics = {
  foundations: {title:'One-step equations',description:'Build your confidence with addition, subtraction, and multiplication.',example:'x + 7 = 15'},
  linear: {title:'Two-step equations',description:'Undo operations in the right order to isolate the variable.',example:'3x + 4 = 19'},
  both: {title:'Variables on both sides',description:'Bring like terms together and find the balance.',example:'5x + 2 = 2x + 14'},
  brackets: {title:'Distributive property',description:'Expand brackets, simplify, and solve.',example:'2(x + 3) = 18'}
};
let mathSession = null;
const randomInt = (min,max) => Math.floor(Math.random()*(max-min+1))+min;
const signedTerm = n => n<0 ? `− ${Math.abs(n)}` : `+ ${n}`;
const coefficient = n => n===1?'x':`${n}x`;
function createAlgebraProblem(topic,difficulty='beginner'){
  if(!Object.hasOwn(algebraTopics,topic))throw Error('Unknown algebra topic');
  const advanced=difficulty==='challenge';
  const answer=randomInt(advanced?-12:1,advanced?12:10), a=randomInt(2,advanced?12:6), b=randomInt(advanced?-15:1,advanced?15:12);
  let equation,hints,steps,lhs,rhs;
  if(topic==='foundations'){
    if(Math.random()<.5){rhs=answer+b;equation=`x ${signedTerm(b)} = ${rhs}`;lhs=x=>x+b;hints=[`Use the inverse operation to undo ${b<0?'subtraction':'addition'}.`,`${b<0?'Add':'Subtract'} ${Math.abs(b)} on both sides.`];steps=[`Start with ${equation}.`,`${b<0?'Add':'Subtract'} ${Math.abs(b)} on both sides to keep the equation balanced.`,`x = ${rhs} ${signedTerm(-b)}`,`x = ${answer}`];}
    else{rhs=a*answer;equation=`${a}x = ${rhs}`;lhs=x=>a*x;hints=['The number next to x means multiplication.',`Divide both sides by ${a}.`];steps=[`Start with ${equation}.`,`Divide both sides by ${a}.`,`x = ${rhs} ÷ ${a}`,`x = ${answer}`];}
  }else if(topic==='linear'){
    rhs=a*answer+b;equation=`${a}x ${signedTerm(b)} = ${rhs}`;lhs=x=>a*x+b;hints=[`First undo the ${b<0?'subtraction':'addition'} outside the x term.`,`${b<0?'Add':'Subtract'} ${Math.abs(b)} on both sides, then divide by ${a}.`];steps=[`Start with ${equation}.`,`${b<0?'Add':'Subtract'} ${Math.abs(b)} on both sides: ${a}x = ${rhs-b}.`,`Divide both sides by ${a}.`,`x = ${answer}`];
  }else if(topic==='both'){
    const c=randomInt(1,a-1),d=(a-c)*answer+b;equation=`${a}x ${signedTerm(b)} = ${coefficient(c)} ${signedTerm(d)}`;lhs=x=>a*x+b;rhs=c*answer+d;hints=[`Move the x terms to one side by subtracting ${coefficient(c)} from both sides.`,`After collecting x terms, undo ${signedTerm(b)} and divide by ${a-c}.`];steps=[`Subtract ${coefficient(c)} from both sides: ${coefficient(a-c)} ${signedTerm(b)} = ${d}.`,`${b<0?'Add':'Subtract'} ${Math.abs(b)} on both sides: ${coefficient(a-c)} = ${d-b}.`,`Divide both sides by ${a-c}.`,`x = ${answer}`];
  }else{
    rhs=a*(answer+b);equation=`${a}(x ${signedTerm(b)}) = ${rhs}`;lhs=x=>a*(x+b);hints=[`Distribute ${a} to both terms inside the brackets.`,`The expanded left side is ${a}x ${signedTerm(a*b)}. Undo the constant, then divide by ${a}.`];steps=[`Distribute ${a}: ${a}x ${signedTerm(a*b)} = ${rhs}.`,`${b<0?'Add':'Subtract'} ${Math.abs(a*b)} on both sides: ${a}x = ${rhs-a*b}.`,`Divide both sides by ${a}.`,`x = ${answer}`];
  }
  return {topic,equation,answer,hints,steps,check:`Substitute x = ${answer} into the original equation. Both sides equal ${rhs}.`,lhs,rhs};
}
function parseMathAnswer(value){const cleaned=value.trim().replace(/^x\s*=\s*/i,'').replace(/−/g,'-');if(/^[+-]?(?:\d+(?:\.\d*)?|\.\d+)$/.test(cleaned))return Number(cleaned);const fraction=cleaned.match(/^([+-]?\d+)\s*\/\s*([+-]?\d+)$/);if(fraction&&Number(fraction[2])!==0)return Number(fraction[1])/Number(fraction[2]);return NaN;}
function renderMath(){show('math');$('#math').innerHTML=`<div class="heading-row"><div><p class="eyebrow">A DIFFERENT WAY TO THINK</p><h1>Your math lab.</h1><p class="subtitle">Work it out. Find the pattern. Make the connection.</p></div><span class="math-badge">∑ MATH</span></div><div class="math-banner"><div><p class="eyebrow">SUBJECT 01</p><h2>Algebra</h2><p>Every unknown is a chance to discover something.</p><p class="math-intro">Solve a problem at a time, get a nudge when you need one, and see the reasoning behind the answer.</p></div><div class="math-art" aria-hidden="true"><span>x</span><span>+</span><span>y</span><i>= possibility</i></div></div><div class="library-toolbar"><h2>Choose your practice</h2><label class="difficulty-label">Difficulty <select id="mathDifficulty"><option value="beginner">Foundations · positive answers</option><option value="challenge">Challenge · include negatives</option></select></label></div><div class="math-topics">${Object.entries(algebraTopics).map(([key,t],i)=>`<button class="math-topic" data-topic="${key}"><span class="topic-number">0${i+1}</span><span class="topic-equation">${esc(t.example)}</span><h3>${esc(t.title)}</h3><p>${esc(t.description)}</p><span class="topic-link">Start solving ↗</span></button>`).join('')}</div><p class="storage-note">Practice at your pace. Each session has 10 problems. Progress is kept for this session.</p>`;}
function startMath(topic){mathSession={topic,difficulty:$('#mathDifficulty')?.value||'beginner',number:0,correct:0,assisted:0,previous:''};nextMathProblem();}
function nextMathProblem(){const s=mathSession;if(s.number===10)return renderMathSummary();s.number++;let p;for(let i=0;i<20;i++){p=createAlgebraProblem(s.topic,s.difficulty);if(p.equation!==s.previous)break;}s.previous=p.equation;s.problem=p;s.hints=0;s.revealed=false;s.finished=false;s.attempts=0;renderMathProblem();}
function renderMathProblem(){show('math');const s=mathSession,p=s.problem;$('#math').innerHTML=`<button class="back-button" id="mathBack">← Algebra topics</button><div class="study-top"><div><p class="eyebrow">MATH / ALGEBRA</p><h2>${esc(algebraTopics[s.topic].title)}</h2></div><span>Problem ${s.number} / 10</span></div><div class="progress"><div style="width:${(s.number-1)*10}%"></div></div><div class="math-workspace"><div class="problem-panel"><p class="eyebrow">FIND THE VALUE OF x</p><div class="problem-equation">${esc(p.equation)}</div><form id="mathAnswerForm"><label for="mathAnswer">Your answer</label><div class="answer-row"><span aria-hidden="true">x =</span><input id="mathAnswer" type="text" inputmode="text" autocomplete="off" placeholder="Enter a number" aria-describedby="answerHelp mathFeedback" required><button class="primary" type="submit">Check answer</button></div><p id="answerHelp">Use a number or fraction, like −3, 2.5, or 1/2.</p></form><div id="mathFeedback" role="status" aria-live="polite"></div><div class="math-help-actions"><button class="secondary" id="mathHint">✧ Give me a hint</button><button class="text-button" id="mathSolution">Show solution</button></div><div id="mathHintBox" class="hint-box" hidden aria-live="polite"></div><div id="mathSolutionBox" class="solution-box" hidden></div><button class="primary math-next" id="mathNext" hidden>${s.number===10?'See results':'Next problem →'}</button></div><aside class="scratch-panel"><span class="eyebrow">THINKING SPACE</span><h3>Make it make sense.</h3><p>Keep both sides balanced. Whatever you do to one side, do to the other.</p><label for="mathNotes">Your working</label><textarea id="mathNotes" placeholder="Try your steps here…&#10;&#10;1. Undo the constant&#10;2. Isolate x&#10;3. Check your answer"></textarea><small>Scratch work clears with each problem.</small><div class="practice-stats"><strong>${s.correct}</strong><span>solved without hints<br>in this session</span></div></aside></div>`;$('#mathAnswerForm').addEventListener('submit',checkMathAnswer);$('#mathHint').onclick=revealMathHint;$('#mathSolution').onclick=revealMathSolution;$('#mathNext').onclick=nextMathProblem;$('#mathBack').onclick=renderMath;$('#mathAnswer').focus();}
function checkMathAnswer(e){e.preventDefault();const s=mathSession;if(s.finished)return;const answer=parseMathAnswer($('#mathAnswer').value),feedback=$('#mathFeedback');if(!Number.isFinite(answer)){feedback.className='math-feedback retry';feedback.textContent='Enter a number or a fraction with a nonzero denominator.';return;}s.attempts++;if(Math.abs(answer-s.problem.answer)<1e-9){s.finished=true;if(!s.hints&&!s.revealed)s.correct++;else s.assisted++;feedback.className='math-feedback success';feedback.textContent=`You’ve got it! x = ${s.problem.answer}. ${s.problem.check}`;$('#mathNext').hidden=false;$('#mathAnswerForm').querySelector('button').disabled=true;$('#mathHint').disabled=true;}else{feedback.className='math-feedback retry';feedback.textContent='Not quite yet. Check the signs and keep both sides balanced. Try again, or ask for a hint.';$('#mathAnswer').select();}}
function revealMathHint(){const s=mathSession;if(s.hints>=s.problem.hints.length)return;const box=$('#mathHintBox');box.hidden=false;s.hints++;box.innerHTML=s.problem.hints.slice(0,s.hints).map((h,i)=>`<p><strong>Hint ${i+1}</strong> ${esc(h)}</p>`).join('');$('#mathHint').textContent=s.hints===s.problem.hints.length?'All hints shown':'One more hint';$('#mathHint').disabled=s.hints===s.problem.hints.length;}
function revealMathSolution(){const s=mathSession;s.revealed=true;const box=$('#mathSolutionBox');box.hidden=false;box.innerHTML=`<h3>Let’s work through it.</h3><ol>${s.problem.steps.map(step=>`<li>${esc(step)}</li>`).join('')}</ol><p>${esc(s.problem.check)}</p>`;if(!s.finished){s.finished=true;s.assisted++;$('#mathFeedback').className='math-feedback';$('#mathFeedback').textContent='Solution reviewed. Try the next problem to practice the same idea.';}$('#mathAnswerForm').querySelector('button').disabled=true;$('#mathHint').disabled=true;$('#mathSolution').disabled=true;$('#mathNext').hidden=false;}
function renderMathSummary(){const s=mathSession;$('#math').innerHTML=`<div class="result"><p class="eyebrow">ALGEBRA / SESSION COMPLETE</p><h1>You connected the dots.</h1><p>${esc(algebraTopics[s.topic].title)} · 10 problems completed</p><div class="math-results"><div><strong>${s.correct}</strong><span>Solved without hints</span></div><div><strong>${s.assisted}</strong><span>With hints or a solution</span></div></div><p>Every step is practice. Keep building on what you know.</p><div class="study-controls"><button class="secondary" id="mathTopics">Choose a topic</button><button class="primary" id="mathAgain">Practice again ↗</button></div></div>`;$('#mathTopics').onclick=renderMath;$('#mathAgain').onclick=()=>{mathSession={topic:s.topic,difficulty:s.difficulty,number:0,correct:0,assisted:0,previous:''};nextMathProblem();};}
$('#mathNav').onclick=renderMath;
$('#math').addEventListener('click',e=>{const topic=e.target.closest('[data-topic]');if(topic)startMath(topic.dataset.topic);});
