const {readFileSync}=require('node:fs');
const vm=require('node:vm');
const assert=require('node:assert/strict');
const elements=new Map();
const element=selector=>{if(!elements.has(selector))elements.set(selector,{addEventListener(){},value:'',hidden:false});return elements.get(selector);};
const context=vm.createContext({document:{querySelector:element,addEventListener(){}},crypto:require('node:crypto').webcrypto,setTimeout,clearTimeout,console});
vm.runInContext(readFileSync(__dirname+'/app.js','utf8').replace(/init\(\);\s*$/,''),context);
const run=code=>vm.runInContext(code,context);
const json=code=>JSON.parse(JSON.stringify(run(code)));
context.csv = 'term,definition\r\n"a,b","line 1\nline 2"\r\n"say ""hi""",answer';
assert.deepEqual(json('parseDelimited(csv, ",")'),[['term','definition'],['a,b','line 1\nline 2'],['say "hi"','answer']]);
context.tsv = 'hola\thello\n';
assert.deepEqual(json('parseDelimited(tsv, "\\t")'),[['hola','hello']]);
assert.throws(()=>run(`parseDelimited('"unclosed', ',')`));
assert.equal(run(`safeImage('javascript:alert(1)')`),'');
assert.equal(run(`safeImage('data:image/svg+xml;base64,AAAA')`),'');
assert.equal(run(`esc('<img onerror="x">')`),'&lt;img onerror=&quot;x&quot;&gt;');
const backup={format:'brian-study',version:1,sets:[{title:'Test',cards:[{front:'Term',back:'Answer',frontImage:'data:image/png;base64,AAAA'}]}]};
context.backup=backup;
const imported=json('validateImported(backup)');
assert.equal(imported[0].cards[0].frontImage,backup.sets[0].cards[0].frontImage);
assert.notEqual(run('validateImported(backup)[0].id'),imported[0].id);
context.invalid={...backup,sets:[{title:'Empty',cards:[{front:'',back:'Answer'}]}]};
assert.throws(()=>run('validateImported(invalid)'));
context.invalid={...backup,sets:[{title:'Bad image',cards:[{front:'Term',back:'Answer',backImage:'https://example.com/image.png'}]}]};
assert.throws(()=>run('validateImported(invalid)'));
assert.throws(()=>run('validateImported({format:"brian-study",version:2,sets:[]})'));
assert.deepEqual(json('shuffled([1,2,3,4]).sort()'),[1,2,3,4]);
context.sourceSets=[{id:'one',title:'Same title',description:'Quotes "and", commas\nwith lines',cards:[{front:'What is "memory", exactly?\nThink deeply.',back:'記憶 🧠',frontImage:'data:image/png;base64,AAAA',backImage:''}]},{id:'two',title:'Same title',description:'Different set',cards:[{front:'',back:'An image-only question',frontImage:'data:image/jpeg;base64,AAAA',backImage:''}]}];
const restored=json("validateImported(importDelimited(setsToCsv(sourceSets),'backup.csv'))");
assert.equal(restored.length,2);
for(let i=0;i<2;i++){assert.equal(restored[i].title,context.sourceSets[i].title);assert.equal(restored[i].description,context.sourceSets[i].description);assert.deepEqual(restored[i].cards,context.sourceSets[i].cards);}
assert.equal(json("validateImported(importDelimited('term,definition\\nHola,Hello','Spanish.csv'))")[0].cards[0].back,'Hello');
assert.equal(json("validateImported(importDelimited('Hola,Hello','Spanish.csv'))")[0].title,'Spanish');
assert.throws(()=>run("validateImported(importDelimited('term,definition','empty.csv'))"));
assert.throws(()=>run("importDelimited('set_id,term,definition\\na,b,c','bad.csv')"));
assert.throws(()=>run("importDelimited('a,b,c','bad.csv')"));
console.log('Passed: full CSV round-trip with images, multiple sets with identical titles, Unicode, quotes and multiline text; simple CSV imports; malformed imports; legacy backups; image validation; escaping; shuffle.');
